### ISSUE TITLE
[EXAMPLE REQUEST] dash-iconify example app

### ISSUE THREAD

**Issue by andrew-hossack** [snehilvj/dash-iconify#1]
Hello,

I'm writing both `dash-iconify` (and [dash-mantine-components](https://github.com/snehilvj/dash-mantine-components)) into my dash command line tool for creating and deploying apps, and want to know if you had an example dash-iconify app you would like to share that highlights the features of iconify. I'd love to include it as an app template for users. Love the work you have been doing!

[Here](https://github.com/andrew-hossack/dash-tools) is a link to my project, if you are interested.

Thanks,
Andrew

**Comment by snehilvj** [comment]
Hi @andrew-hossack, I came across your project sometime back and I like what you are doing. Thanks for including dmc and dash iconify.
* `dash-iconify` : I am not sure if a standalone template which uses just dash-iconify makes sense. It's more like a utility. But let me know your thoughts.
* `dmc` : If you are willing, I can come up with more examples to address the following using dmc:
    * side nav bar
    * dark theme
    * dmc with dash-iconify
    * responsive top navigation
    * any other use case you can think of

PS: We can move this issue to dash-tools if you prefer that.

**Comment by andrew-hossack** [comment]
Thanks for the reply!

> dash-iconify : I am not sure if a standalone template which uses just dash-iconify makes sense. It's more like a utility. But let me know your thoughts.

You're right, if we could roll `dash-iconify` into a new Dash project with `dmc` it could show off the functionality better.

> dmc : If you are willing, I can come up with more examples to address the following using dmc:

Huge fan of that idea!

> PS: We can move this issue to dash-tools if you prefer that.

Sure, let's move to https://github.com/andrew-hossack/dash-tools/issues/21, thanks for the help!

**Comment by andrew-hossack** [comment]
Hi @snehilvj, happy to have your help. I will close this issue now and move to dash-tools issue.
