### ISSUE TITLE
Thanks! How does it work?

### ISSUE THREAD

**Issue by aiqc** [snehilvj/dash-iconify#2]
Hiya. Love this library ⭐ . Jazzing up my buttons.
Would you mind putting a bit about how it works into the readme? 

- Does it inject a `<script>` into the layout? 
- Does it inject a `Dash(external_stylesheets=[i])`?
- Does it use a cdn? 1 centrally/ many cdns? require internet connection?
- Does it download any static assets?

**Comment by aiqc** [comment]
it would also be good to mention that it supports `className` attribute

**Comment by snehilvj** [comment]
Thanks @aiqc and apology for such a delayed reply. Thanks for the feedback. I'll add these in the readme and docs.
