### ISSUE TITLE
Color parameter does not work with openmoji

### ISSUE THREAD

**Issue by kayjan** [snehilvj/dash-iconify#4]
Hi, I'm trying to use DashIconify with openmoji and I cannot get the black variant of the icon

Link to icon: https://openmoji.org/library/emoji-E100/#variant=black
Code: `DashIconify(icon="openmoji:tap", color="black", height=40)`

**Comment by snehilvj** [comment]
It's actually not about the color but the fill of the icon. Iconfiy doesn't have any way to allow for toggling between fill and outline unless two separate icons exist for them in the icon set. Hence, the color prop won't work here.
